server:
  port: 8888

spring:
  application:
    name: guet-provide
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: dev

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guet?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#  data:
#    redis:
#      host: localhost
#      port: 6379




mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

